package com.kernacs.tweetfinder.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006d3c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF6ffdaa)
val md_theme_light_onPrimaryContainer = Color(0xFF00210e)
val md_theme_light_secondary = Color(0xFF626200)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFeaea00)
val md_theme_light_onSecondaryContainer = Color(0xFF1d1d00)
val md_theme_light_tertiary = Color(0xFF8f4e00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdcbf)
val md_theme_light_onTertiaryContainer = Color(0xFF2e1500)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf7)
val md_theme_light_onBackground = Color(0xFF191c1a)
val md_theme_light_surface = Color(0xFFfbfdf7)
val md_theme_light_onSurface = Color(0xFF191c1a)
val md_theme_light_surfaceVariant = Color(0xFFdce5db)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1ec)
val md_theme_light_inverseSurface = Color(0xFF2e312e)

val md_theme_dark_primary = Color(0xFF4fe090)
val md_theme_dark_onPrimary = Color(0xFF00391c)
val md_theme_dark_primaryContainer = Color(0xFF00522b)
val md_theme_dark_onPrimaryContainer = Color(0xFF6ffdaa)
val md_theme_dark_secondary = Color(0xFFcdcd00)
val md_theme_dark_onSecondary = Color(0xFF323200)
val md_theme_dark_secondaryContainer = Color(0xFF4a4900)
val md_theme_dark_onSecondaryContainer = Color(0xFFeaea00)
val md_theme_dark_tertiary = Color(0xFFffb774)
val md_theme_dark_onTertiary = Color(0xFF4d2700)
val md_theme_dark_tertiaryContainer = Color(0xFF6d3a00)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdcbf)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1a)
val md_theme_dark_onBackground = Color(0xFFe1e3de)
val md_theme_dark_surface = Color(0xFF191c1a)
val md_theme_dark_onSurface = Color(0xFFe1e3de)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c9c0)
val md_theme_dark_outline = Color(0xFF8b938b)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1a)
val md_theme_dark_inverseSurface = Color(0xFFe1e3de)

val seed = Color(0xFF2ec77a)
val error = Color(0xFFba1b1b)