name: verify PR and main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: API keys to local.properties
        env:
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          LIFESPAN_IN_MILLISECONDS: ${{secrets.LIFESPAN_IN_MILLISECONDS}}
        run: |
          echo '' >> ./local.properties
          echo BEARER_TOKEN="BEARER_TOKEN" >> ./local.properties
          echo LIFESPAN_IN_MILLISECONDS="LIFESPAN_IN_MILLISECONDS" >> ./local.properties
      - name: build debug
        run: ./gradlew assembleDebug --stacktrace

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: API keys to local.properties
        env:
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          LIFESPAN_IN_MILLISECONDS: ${{secrets.LIFESPAN_IN_MILLISECONDS}}
        run: |
          echo '' >> ./local.properties
          echo BEARER_TOKEN="$BEARER_TOKEN" >> ./local.properties
          echo LIFESPAN_IN_MILLISECONDS="$LIFESPAN_IN_MILLISECONDS" >> ./local.properties
      - name: Run Unit Tests
        run: ./gradlew test
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace
